catdex/urls.py
from django.urls import path
from .views import *

app_name = 'catdex'

urlpatterns = [
    path('', show_catdex, name='show_catdex'),
    path('<subcategory_slug>/',show_catdex,name='show_catdex')
]

catphoto/urls.py
from django.urls import path
from .views import *

app_name = 'catphoto'

urlpatterns = [
    path('', show_catphoto, name='show_catphoto'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('catdex/', include('catdex.urls')),
    path('catphoto/', include('catphoto.urls')),
    path('introduction/', include('introduction.urls')),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

introduction/urls.py
from django.urls import path
from .views import *

app_name = 'introduction'

urlpatterns = [
    path('', show_introduction, name='show_introduction'),
    path('<category_slug>/',show_introduction,name='show_introduction'),
]

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
]

catdex/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name=models.CharField(max_length=200,db_index=True)
    slug=models.SlugField(max_length=200,db_index=True,unique=True,allow_unicode=True)
    
    class Meta:
        ordering=['name']
        verbose_name='category'
        verbose_name_plural='categories'

    def __str__(self):
        return self.name
    
    #def get_absolute_url(self):
    #    return reverse('catdex:show_catdex',args=[self.slug])

class Subcategory(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE,null=True,related_name='subcategories')
    name=models.CharField(max_length=200,db_index=True)
    slug=models.SlugField(max_length=200,db_index=True,unique=True,allow_unicode=True)
    class Meta:
        ordering=['category','name']
        verbose_name='subcategory'
        verbose_name_plural='subcategories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catdex:show_catdex',args=[self.slug])

class Cat(models.Model):
    
    DOMAIN=(
        ('쪽문','쪽문'),('서문','서문'),('솔로문','솔로문'),('동문','동문'),('대학원동','대학원동'),
        ('화학관','화학관'),('향토/첨성','향토/첨성')
    )
    GENDER=(
        ('암컷','암컷'),('수컷','수컷')
    )
    TNR=(
        ('중성화YES','중성화YES'),('중성화NO','중성화NO')
    )
    COLOR=(
        ('치즈','치즈'),('고등어','고등어'),('삼색','삼색'),('검정','검정'),('카오스','카오스')
    )
    INTIMACY=(
        ('상','상'),('중','중'),('하','하')
       )
    subcategory=models.ManyToManyField(Subcategory,blank=True,related_name='cat')
    name=models.CharField(max_length=200,db_index=True)
    slug=models.SlugField(max_length=200,db_index=True,unique=True,allow_unicode=True)
    image=models.ImageField(upload_to='cat/%Y/%m/%d',blank=True)
   
    gender=models.CharField(max_length=200,db_index=True,choices=GENDER)
    tnr=models.CharField(max_length=200,db_index=True,choices=TNR)
    domain=models.CharField(max_length=200,choices=DOMAIN)
    color=models.CharField(max_length=200,db_index=True,choices=COLOR)
    intimacy=models.CharField(max_length=200,db_index=True,choices=INTIMACY)
    
    description=models.TextField(blank=True)
    created=models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering=['-created']
        index_together=[['id','slug']]

    def __str__(self):
        return self.name

catphoto/models.py
from django.db import models

# Create your models here.

introduction/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    title=models.CharField(max_length=200,db_index=True)
    slug=models.SlugField(max_length=200,db_index=True,unique=True,allow_unicode=True)

    class Meta:
        ordering=['title']
        verbose_name='category'
        verbose_name_plural='categories'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('introduction:show_introduction',args=[self.slug])

class Introduction(models.Model):
    category=models.ForeignKey(Category,on_delete=models.SET_NULL,null=True,related_name='introductions')
    title=models.CharField(max_length=200,db_index=True)
    content=models.TextField()
    slug=models.SlugField(max_length=200,db_index=True,unique=True,allow_unicode=True)

    class Meta:
        ordering=['category']

    def __str__(self):
        return self.title
    
    

main/models.py
from django.db import models

# Create your models here.

catdex/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import *

# Create your views here.
def show_catdex(request,subcategory_slug=None):
    current_category=None
    categories=Category.objects.all()
    subcategories=Subcategory.objects.all()
    cats=Cat.objects.all()

    if subcategory_slug:
        current_category=get_object_or_404(Subcategory,slug=subcategory_slug)
        cats=cats.filter(subcategory=current_category)
    return render(request, 'catdex/dex.html',{'current_category':current_category,'categories':categories,'cats':cats,'subcategories':subcategories})

catphoto/views.py
from django.shortcuts import render, redirect
from .models import *

# Create your views here.
def show_catphoto(request):
    # 코딩합시다.

    return render(request, 'catphoto/photo.html',)

introduction/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *

# Create your views here.
def show_introduction(request,category_slug=None):
    current_category=None
    categories=Category.objects.all()
    introductions=Introduction.objects.all()

    if category_slug:
        current_category=get_object_or_404(Category,slug=category_slug)
        introductions=introductions.filter(category=current_category)

    return render(request, 'introduction/intro.html',{'current_category':current_category,'categories':categories,'introductions':introductions})

main/views.py
from django.shortcuts import render, redirect
from .models import *

# Create your views here.
def show_main(request):
    # 코딩합시다.

    return render(request, 'main/index.html',)

catdex/templates/catdex/dex.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'catdex/catdex_style.css' %}"> 

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script type="text/javascript">
    $(function(){
        $("ul.menu li").mouseover(function(){
            $(">ul",this).slideDown("fast");
        }),
        $("ul.menu li").mouseleave(function(){
            $(">ul",this).slideUp("fast");
        });
    });
</script>
<div class="container">
    <div class="category_bar">
        <div class="list-group">
            <ul>
            <li><a href="/catdex" class="list-group-item {% if not current_category %}active{% endif %}" >All</a></li> 
            </ul>
            {% for c in categories %}
            <ul class="menu" style="list-style-type: none;">
                <li>{{c.name}}
                    <ul class="sub" >
                    {% for sc in subcategories %}
                    {% if sc.category.name == c.name %}
                    <li>
                        <a href="{{sc.get_absolute_url}}" class="list-group-sub" >{{sc.name}}</a>
                    </li>
                    {% endif %}
                    {% endfor %}
                    </ul>
                </li>
            </ul>
            {% endfor %}
        </div>
    </div>
    <div class="content_bar">
        <div class="content-name">
            {% if current_category %}{{current_category.name}}{% else %}All Cats{% endif %}
        </div>
        <div class="row">
            {% for cat in cats %}
                <div class="card">
                    <img class="card-img-top" src="{{cat.image.url}}"alt="Cat Image">
                    <div class="card-body">
                        <p class="card-title">{{cat.name}}</p>
                        <p class="card-text">색깔: {{cat.color}}</p>
                        <p class="card-text">영역: {{cat.domain}}</p>
                        <p class="card-text">친밀도: {{cat.intimacy}}</p>
                        <p class="card-text">성별: {{cat.gender}}</p>
                        <p class="card-text">tnr: {{cat.tnr}}</p>
                        <p class="card-text">{{cat.description|linebreaksbr}}</p>
                    </div>
                </div>
            
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

catphoto/templates/catphoto/photo.html
{% extends 'base.html' %}

{% block content %}
<h2>이것이 냥이한컷</h2>
{% endblock %}

introduction/templates/introduction/intro.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="/static/introduction/intro_style.css"> 

<div class="container">
    <div class="category_bar">
        <div class="list-group">
            <ul>
            <li><a href="/introduction" >All</a></li> 
            </ul>
            {% for c in categories %}
            <ul>
            <li><a href="{{c.get_absolute_url}}">{{c.title}}</a>
            </ul>
            {% endfor %}
        
        </div>
    </div>
    <div class="content_bar">
        <div class="content-name">
            {% if current_category %}{{current_category.title}}{% else %}All{% endif %}
        </div>
        <div class="row">
            {% for intro in introductions %}
            <div class="col-4">
                <div class="card">
                    <div class="card-body">
                        <p class="card-title">{{intro.title}}</p>
                        <p class="card-text">{{intro.content|linebreaksbr|urlize}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'base.html' %}

{% block head %}
<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=n481zzescl"></script>
{% endblock %}

{% block content %}
{% load static %}
<script src="{% static 'main/map.js' %}"></script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Do+Hyeon&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <title>크누냥이{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'base_style.css' %}">
    {% block head %}
    {% endblock %}
</head>
<body>
    <div id="nav">
        <span id="knu_map">크누냥이</span>
        <span id="menu">
            <div id="umenu">
                <div class="m" id="m1"><a href="{% url 'introduction:show_introduction' %}">소개</a></div>
                <div class="m" id="m2"><a href="{% url 'catphoto:show_catphoto' %}">냥이한컷</a></div>
                <div class="m" id="m3"><a href="{% url 'catdex:show_catdex' %}">크냥도감</a></div>
                <div class="m" id="m4"><a href="{% url 'main:show_main' %}">크냥맵</a></div>
            </div>
        </span>
        <span id="menu_m">
            <i id="icon" class="fa fa-bars fa-4x"></i>
            <div id="umenum">
                <div class="m" id="m1m"><a href="{% url 'main:show_main' %}">크냥맵</a></div>
                <div class="m" id="m2m"><a href="{% url 'catdex:show_catdex' %}">크냥도감</a></div>
                <div class="m" id="m3m"><a href="{% url 'catphoto:show_catphoto' %}">냥이한컷</a></div>
                <div class="m" id="m4m"><a href="{% url 'introduction:show_introduction' %}">소개</a></div>
            </div>
        </span>
    </div>
    <div id="map">
    {% block content %}

    {% endblock %}
    </div>
    <div id="footer">
        <div id="wrapper">
            <span>메일주소무단수집거부</span><br>

            <span>대구광역시 북구 산격3동(대학로80) 경북대학교 IT-1호관 108호</span><br>
            <span>Email : </span><br>

            <span>copyright © 경북대학교 IT대학 학술동아리 해달, All Rights Reserved</span><br>
            <span>기획 :  | 개발 : </span>
        </div>
    </div>
    <script src="{% static 'base.js' %}"></script>
</body>
</html>